apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u5e0uyfs4-python
  janus-idp.io/tekton: u5e0uyfs4-python
  backstage.io/kubernetes-id: u5e0uyfs4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u5e0uyfs4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
